# Generated by Django 6.0.2 on 2026-03-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='employees/')),
            ],
        ),
    ]
